// Components/gameData.js
// Единый источник фраз/заданий и "желаний" + генератор хода

// ассеты (пути из /assets)
const ICON_DOUBLE = require('../assets/double_task.webp');
const ICON_CAR    = require('../assets/car.webp');
const ICON_BOAT   = require('../assets/boat.webp');

// --- Пулы заданий ---
const TASKS_SEA = [
  'Sing a song about the sea.',
  'Imitate rowing.',
  'Tell a sea legend.',
  'Show how you are being tossed by the waves.',
  'Pretend you are the captain of a ship.',
  'Shout “I am the captain tonight!”',
  'Come up with a name for your ship.',
  'Shout “SOS!” as if you can be heard from the island.',
  'Show how you catch fish with your hands.',
  'Imitate a dolphin.',
  'Show how you relax on a yacht.',
  'Think of who you would take on a sea voyage.',
  'Give a speech like a real pirate.',
  'Name each player in a pirate voice.',
  'Show how you jump into the water.',
  'Sing “Under the Sea” in your own style.',
  'Make a wave with your hands.',
  'Show how you are being tossed by a storm.',
  'Imitate a seagull.',
  'Say “My boat is the best!” with pathos.',
  'Ask everyone for a “ship ticket.”',
  'Imagine what you see on the horizon.',
  'Imitate the sound of a boat engine.',
  'Pretend you fell overboard.',
  'Describe what the party would be like on a ship.',
  'Shout “Lighthouse ahead!”',
  'Come up with your own nautical rule.',
  'Call yourself the captain and appoint your assistant.',
  'Imitate the wind blowing in your hair.',
  'Show how you drop anchor.',
  'Take a selfie as if you are on deck.',
  'Shout “Land ho!”',
  'Name your ship “Invincible.”',
  'Show how you dance on the waves.',
  'Imitate the sound of the surf.',
  'Raise an imaginary flag.',
  'Say “A sea bull doesn’t sink!”',
  'Make up a toast for sailors.',
  'Pretend to throw a lifebuoy.',
  'Imitate a sea breeze.',
  'Make up your own nautical slang.',
  'Pretend to steer a ship.',
  'Shout “Here we go!”',
  'Describe your ideal beach.',
  'Show yourself sunbathing on a boat.',
  'Imitate waves with your body.',
  'Make up a new nautical dance.',
  'Say “A sea bull is a success!”',
  'Make up a scene about a ghost ship.',
  'Make up a nautical nickname for your neighbor.',
];

const TASKS_CAR = [
  'Imitate the sound of an engine.',
  'Pretend to be driving.',
  'Show how you stop at a traffic light.',
  'Say the phrase “I park perfectly!”',
  'Imitate a car horn.',
  'Name your favorite brand of car.',
  'Make the engine roar with your voice.',
  'Show how you are being overtaken.',
  'Imitate a car starting for the third time.',
  'Come up with a new name for a car.',
  'Say a phrase that a taxi driver would say.',
  'Imitate a novice driver.',
  'Imitate a car braking.',
  'Name your imaginary license plate.',
  'Pretend to listen to the radio while driving.',
  'Show how you fill up your car.',
  'Say “I am a parking champion!”',
  'Imitate a driver in a traffic jam.',
  'Show how you wash your car.',
  'Imitate skidding tires.',
  'Say “My bull is the Ferrari of the soul!”',
  'Pretend to open the window.',
  'Name the song playing in your car.',
  'Imitate a car flying down the highway.',
  'Say the phrase “I’m almost there!”',
  'Think of what your car would say.',
  'Pretend to be stopped by the police.',
  'Imitate the sounds of turning corners.',
  'Act out being hit by potholes.',
  'Imitate a nighttime drive.',
  'Think of a name for your car.',
  'Sing an imaginary song about roads.',
  'Say “The bull on the highway is me!”',
  'Imitate a GPS navigator with errors.',
  'Pretend your car is talking.',
  'Act out how you get out after a long drive.',
  'Pretend that the car won\'t start.',
  'Imitate a driver with a "Friday" mood.',
  'Come up with a name for your driving style.',
  'Show how you praise your car.',
  'Say "Bull behind the wheel - maximum luck!".',
  'Imitate a car race.',
  'Pretend that you are filming a car commercial.',
  'Say "I love the smell of gasoline in the morning."',
  'Show how you win a race.',
  'Imitate a car flying into space.',
  'Think of where you will go after the party.',
  'Say a phrase that a mechanic would say.',
  'Imitate your favorite track playing in the car.',
  'Show how you roll out of the car "like in a movie."',
];

const TASKS_GENERAL = [
  'Do 5 sit-ups and tell a joke.',
  'Jump up three times and shout “BULL’S DARE EYE!”',
  'Name a player and compliment them.',
  'Come up with a rhyme for the word “bull.”',
  'Go up to the wall and bow like a champion.',
  'Come up with an impromptu toast.',
  'Complete two tasks in a row (this and the next).',
  'Say a funny phrase in the voice of a news anchor.',
  'Come up with a motto for the game.',
  'Act out how you would win a TV show.',
  'Sing a short song about a bull.',
  'Imitate the host of a party.',
  'Name three things you love.',
  'Come up with an idea for a new task.',
  'Read a random word like a spell.',
  'Act out if you were a celebrity.',
  'Mimic your morning routine in 5 seconds.',
  'Pick up any object and pretend it\'s a microphone.',
  'Make your neighbor laugh.',
  'Mimic a superstar\'s laugh.',
  'Come up with a new sound for a bull.',
  'Name a color that describes your mood.',
  'Show your best dance.',
  'Pretend you\'re a TV presenter.',
  'Come up with a nickname for yourself in a game.',
  'Pretend you\'re in a shampoo commercial.',
  'Come up with a new name for a game.',
  'Show your "happy pose".',
  'Name your superhero nickname.',
  'Mimic a bull\'s bellow.',
  'Tell a short joke.',
  'Say something with a British accent.',
  'Come up with a name for a party.',
  'Mimic a fanfare sound.',
  'Take a selfie with the funniest pose.',
  'Say “I was born for challenges!”',
  'Name three random things in the room.',
  'Imitate a movie character.',
  'Come up with your own award and who to give it to.',
  'Show how you celebrate a victory.',
  'Come up with a name for the bull-player.',
  'Imitate the emotion “won”.',
  'Tell a story in 5 words.',
  'Sing without music.',
  'Say “I have two tasks - to complete everything!”',
  'Come up with a new game feature.',
  'Make two different sounds in a row.',
  'Imitate the voice of a bear and a cat at the same time.',
  'Name your favorite song.',
  'Come up with a phrase for the finale of the show.',
  'Pretend you are a TV presenter.',
  'Say three words about your day.',
  'Pretend you are in a coffee commercial.',
  'Imitate a scared player.',
  'Say “Double Task? Easy peasy!”',
  'Do the worst dance you can.',
  'Come up with a motivational phrase.',
  'Pretend you won the jackpot.',
  'Name three things about yourself that you love.',
  'Tell a random story from your childhood.',
  'Come up with a new move for a bull.',
  'Pretend you’re playing a game of “guess the emotion.”',
  'Say “Bull’s Dare Eye is the best show!”',
  'Do the winning pose.',
  'Name a person who should do the challenge with you.',
  'Come up with your own victory sound.',
  'Imitate a sports announcer.',
  'Come up with a short motto for the game.',
  'Say “Double Task is my style!”',
  'Show what luck looks like.',
  'Mimic the sounds of applause.',
  'Name three random countries.',
  'Pretend you’re in a water commercial.',
  'Come up with your own dance move.',
  'Say a phrase like the game host.',
  'Come up with a bull’s superpower.',
  'Imitate a robot.',
  'Name what you would do if you won the game.',
  'Imitate thunder and lightning.',
  'Say the phrase, “My move is double!”',
  'Act out a “double challenge” with your gestures.',
  'Sing “Bull’s Power!”',
  'Imitate an 80s TV show host.',
  'Come up with two tasks for the next player.',
  'Pretend to throw a dart.',
  'Come up with a name for a new game mode.',
  'Act out if the bull were dancing.',
  'Imitate yourself when you win.',
  'Strike a “mega-hero” pose.',
  'Name your “Bull Level.”',
  'Say “I have double the power!”',
  'Come up with a short slogan for the game.',
  'Mimic the applause of fans.',
  'Pretend you are advertising the app.',
  'Mimic the voice of Siri giving a task.',
  'Come up with a new sound for the game.',
  'Say “I am a bull - I can do anything!”',
  'Come up with a name for your avatar.',
  'Mimic your “lucky win”.',
  'Do a double task: any of the previous ones + a funny pose.',
];

// Элементы (объект + иконка + связанный пул)
const ELEMENTS = [
  { key: 'sea',  icon: ICON_BOAT,   tasks: TASKS_SEA },
  { key: 'car',  icon: ICON_CAR,    tasks: TASKS_CAR },
  { key: 'fun',  icon: ICON_DOUBLE, tasks: TASKS_GENERAL }, // нейтральный пул
];

// Генерация хода: случайный элемент и 1–2 задания из его пула
function generateTurn() {
  const element = ELEMENTS[Math.floor(Math.random() * ELEMENTS.length)];
  const pool = element.tasks;
  const first = pool[Math.floor(Math.random() * pool.length)];
  const isDouble = Math.random() < 0.35;
  const items = [first];

  if (isDouble) {
    let second = first;
    while (second === first) {
      second = pool[Math.floor(Math.random() * pool.length)];
    }
    items.push(second);
  }
  return { element, items, double: isDouble };
}

// --- Желания (Wish the Box) ---
const WISHES = [
  'Everyone has to say something nice about the person who made the wish.',
  'The team has to make up a song about that player and sing one line.',
  'Everyone has to repeat a funny phrase that you came up with.',
  'One of the players has to tell a short joke especially for you.',
  'Everyone has to make the weirdest face at the same time.',
  'One player has to compliment you as if it were a formal speech.',
  'Everyone has to call you the new “Bull” for the next round.',
  'The team has to come up with a new name or nickname for you.',
  'Everyone has to tell you why they would invite you to their team.',
  'One of the players has to read something like a show host in your honor.',
  'Everyone has to show the emotion of “happiness” at the same time.',
  'Each player says a phrase of support to you - but with a strange intonation.',
  'Someone has to imitate you for 10 seconds.',
  'All players must pretend to take a photo with you for a “magazine cover.”',
];

// Экспорты
export {
  ICON_DOUBLE,
  ELEMENTS,
  WISHES,
  TASKS_SEA,
  TASKS_CAR,
  TASKS_GENERAL,
  generateTurn,
};
export default { ICON_DOUBLE, ELEMENTS, WISHES, generateTurn };
